export const GET_NOTES_LOADING = "GET_NOTES_LOADING";
export const GET_NOTES_SUCCESS = "GET_NOTES_SUCCESS";
export const GET_NOTES_ERROR = "GET_NOTES_ERROR";

export const CREATE_NOTE_LOADING = "CREATE_NOTE_LOADING";
export const CREATE_NOTE_SUCCESS = "CREATE_NOTE_SUCCESS";
export const CREATE_NOTE_ERROR = "CREATE_NOTE_ERROR";

export const EDIT_NOTE_LOADING = "EDIT_NOTE_LOADING";
export const EDIT_NOTE_SUCCESS = "EDIT_NOTE_SUCCESS";
export const EDIT_NOTE_ERROR = "EDIT_NOTE_ERROR";

export const DELETE_NOTE_LOADING = "DELETE_NOTE_LOADING";
export const DELETE_NOTE_SUCCESS = "DELETE_NOTE_SUCCESS";
export const DELETE_NOTE_ERROR = "DELETE_NOTE_ERROR";

export const ADD_NOTE = "ADD_NOTE";

export const SNACKBAR_OPEN = "SNACKBAR_OPEN";
export const SNACKBAR_CLOSE = "SNACKBAR_CLOSE";

export const CLEAR_ERROR = "CLEAR_ERROR";
